### PR TITLE
add python3 code

### PR DESCRIPTION
**Pull request by Matanley**
I am starting this book and want to add all codes written in Python 3.x. Though I just started this book and these changes may be trivial, it still may help those who start with Python 3.x but found this book written on Python 2.x

### CODE REVIEW

**Comment by egonSchiele** [comment]
This is a great idea. Could you put them in a `python3` directory instead of appending `python3` to the file name, to make them all easier to find?

**Comment by Matanley** [comment]
Thank you for the replying, I saw you also merged several commits which changed the print function into python 3. Should I proceed to write python 3 code and commit?

**Comment by harukou** [comment]
Good job!

**Comment by Matanley** [comment]
Currently I am in the middle of other projects and had reached chapter 7 of this book. Later I will return back from the beginning and add the codes under python3 directory. If someone initiate that before me, I will also help the commit. Thank you!

**Pull request closed without merging**
